#!/usr/bin/env python3

IMAGE_WIDTH = 64
IMAGE_HEIGHT = 64
CHANNELS = 3
PREPROCESSED_LAYERS = 4
EPOCHS = 25
PRETRAIN_EPOCHS = 2
BATCH_SIZE = 500
BATCH_SIZE_VALIDATION = 100
STEPS_PER_EPOCH = 100
CATEGORIES = 2
OPACITY_MIN = 0.3
OPACITY_MAX = 0.8
OPACITY_PRETRAIN_MIN = 0.7
OPACITY_PRETRAIN_MAX = 0.8
BOX_SIZE_REL = 0.2
STRIDE_WIDTH = 8
STRIDE_HEIGHT = 8
STRIDE_TRAIN_WIDTH = IMAGE_WIDTH
STRIDE_TRAIN_HEIGHT = IMAGE_HEIGHT
